FROM projectdiscovery/naabu:latest as naabu

FROM projectdiscovery/subfinder:latest as subfinder

FROM projectdiscovery/httpx:latest as httpx

FROM projectdiscovery/nuclei:latest as nuclei

FROM ubuntu:latest
COPY --from=naabu /usr/local/bin/naabu /usr/local/bin
COPY --from=subfinder /usr/local/bin/subfinder /usr/local/bin
COPY --from=httpx /usr/local/bin/httpx /usr/local/bin
COPY --from=nuclei /usr/local/bin/nuclei /usr/local/bin

RUN mkdir /scan
WORKDIR /scan

CMD ["nuclei", "-ut"]

ENTRYPOINT ["/bin/bash"]