#!/usr/bin/bash

OSURL="$1"
OSUSER="$2"
OSPASSWD="$3"

TF_NUCLEI="./nuclei-targets.txt"
echo -n "" > $TF_NUCLEI

sudo ./naabu -silent -json -l "scan-targets.txt" -config ./naabu-config.yaml -tp 1000 | \
while read -r JSON; do
	IDENTIFIER=$(echo $JSON | md5sum | awk '{print $1}');
	if [[ -z "$JSON" ]]; then
		echo "$IDENTIFIER - $TARGET - NO DETECTIONS";
	else 
		IP=$(jq -r '.ip' <<< "$JSON")
		PORT=$(jq -r '.port' <<< "$JSON")
		curl -u "$OSUSER:$OSPASSWD" -k -XPOST "$OSURL-scan-ports/_doc/$IDENTIFIER" --json "$JSON" --silent 1>/dev/null
		echo "$IP:$PORT" >> $TF_NUCLEI;
		echo "$IDENTIFIER - $IP:$PORT - LOGGED FINDING";
	fi
done;

./nuclei -config ./nuclei-scan_config.yaml -l "$TF_NUCLEI"
